news-lets/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using news_lets.BLL;
using news_lets.ViewModels;

namespace news_lets.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ILogger _logger;
        private readonly IAuthorLogic _authorLogic;
        public AuthorController(IAuthorLogic authorLogic,ILogger logger)
        {
            _authorLogic = authorLogic;
            _logger = logger;
        }

        public async Task<IActionResult> List()
        {
            AuthorsShowViewModel authorsShowViewModel = new AuthorsShowViewModel();
            authorsShowViewModel.authorViewModels=await _authorLogic.GetAllAuthorDescriptions();
            return View(authorsShowViewModel);
        }

        public async Task<IActionResult> GetAllAuthorNames()
        {
            List<AuthorNameId> authorNameIds = await _authorLogic.GetAllAuthorNames();
            return Json(authorNameIds);
        }

        public async Task<IActionResult> TopThreeData()
        {
            AuthorsShowViewModel authorsShowViewModel = new AuthorsShowViewModel();
            IEnumerable<AuthorViewModel> authors = (await _authorLogic.GetAllAuthorDescriptions()).OrderByDescending(x=>x.Subscribers).Take(3);
            return Json(authors);
        }

        public async Task<IActionResult> Show(string authorId)
        {
            try { 
                AuthorShowViewModel authorShowViewModel = await _authorLogic.GetAuthorData(authorId);
                foreach (ArticleShowViewModel article in authorShowViewModel.articleShowViewModels)
                {
                    article.Text = article.Text.Replace("<p>", "");
                    article.Text = article.Text.Replace("</p>", "");
                }
                return View(authorShowViewModel);
            }
            catch (Exception ex)
            {
                await _logger.SendError(ex);
                return View("Error");
            }
        }
    }
}

news-lets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @RenderSection("SEO", required: false)
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161491733-1"></script>
    <script src="https://kit.fontawesome.com/36dcb2cd7e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @RenderSection("Styles", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">news_lets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="List">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="List">Articles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Roadmap">Roadmap</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:#fff">
        <div class="container">
            &copy; 2020 - news_lets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<style>
    body {
        background-image: url('/img/back.png');
    }
</style>

<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-161491733-1');
</script>